/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/william-lbn/hypernode/pkg/apis/pml/v1alpha1"
	scheme "github.com/william-lbn/hypernode/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// HyperNodesGetter has a method to return a HyperNodeInterface.
// A group's client should implement this interface.
type HyperNodesGetter interface {
	HyperNodes(namespace string) HyperNodeInterface
}

// HyperNodeInterface has methods to work with HyperNode resources.
type HyperNodeInterface interface {
	Create(ctx context.Context, hyperNode *v1alpha1.HyperNode, opts v1.CreateOptions) (*v1alpha1.HyperNode, error)
	Update(ctx context.Context, hyperNode *v1alpha1.HyperNode, opts v1.UpdateOptions) (*v1alpha1.HyperNode, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.HyperNode, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.HyperNodeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HyperNode, err error)
	HyperNodeExpansion
}

// hyperNodes implements HyperNodeInterface
type hyperNodes struct {
	client rest.Interface
	ns     string
}

// newHyperNodes returns a HyperNodes
func newHyperNodes(c *PmlV1alpha1Client, namespace string) *hyperNodes {
	return &hyperNodes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the hyperNode, and returns the corresponding hyperNode object, and an error if there is any.
func (c *hyperNodes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.HyperNode, err error) {
	result = &v1alpha1.HyperNode{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("hypernodes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of HyperNodes that match those selectors.
func (c *hyperNodes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.HyperNodeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.HyperNodeList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("hypernodes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested hyperNodes.
func (c *hyperNodes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("hypernodes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a hyperNode and creates it.  Returns the server's representation of the hyperNode, and an error, if there is any.
func (c *hyperNodes) Create(ctx context.Context, hyperNode *v1alpha1.HyperNode, opts v1.CreateOptions) (result *v1alpha1.HyperNode, err error) {
	result = &v1alpha1.HyperNode{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("hypernodes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(hyperNode).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a hyperNode and updates it. Returns the server's representation of the hyperNode, and an error, if there is any.
func (c *hyperNodes) Update(ctx context.Context, hyperNode *v1alpha1.HyperNode, opts v1.UpdateOptions) (result *v1alpha1.HyperNode, err error) {
	result = &v1alpha1.HyperNode{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("hypernodes").
		Name(hyperNode.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(hyperNode).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the hyperNode and deletes it. Returns an error if one occurs.
func (c *hyperNodes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("hypernodes").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *hyperNodes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("hypernodes").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched hyperNode.
func (c *hyperNodes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HyperNode, err error) {
	result = &v1alpha1.HyperNode{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("hypernodes").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
